#!/usr/bin/env python3
"""Regenerate TOOL_TRACKER.md — build progress for every calculator.

The tool JSON files are the source of truth: each tool's `status` (planned → in_progress → built →
verified → done) is set in src/content/tools/<slug>.json. This script only reads them and writes a
summary, so the tracker can never disagree with the site. Re-run it after changing any status.

    python3 utilities/scaffold/tool_tracker.py
"""
import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOOLS = ROOT / "src" / "content" / "tools"
CATEGORIES = ROOT / "src" / "config" / "categories.json"
OUT = ROOT / "TOOL_TRACKER.md"

STATUSES = ["planned", "in_progress", "built", "verified", "done"]
SITES = [("calculator.net", "C"), ("dinkytown.net", "D"), ("fncalculator.com", "F")]


def subcategory_names():
    """Subcategory slug -> name, in category page order."""
    names = {}

    def walk(node):
        if isinstance(node, dict):
            if "slug" in node and "name" in node:
                names.setdefault(node["slug"], node["name"])
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    walk(json.loads(CATEGORIES.read_text()))
    return names


def main():
    tools = [json.loads(f.read_text()) for f in sorted(TOOLS.glob("*.json"))]
    subs = subcategory_names()
    order = {slug: i for i, slug in enumerate(subs)}
    by_sub = defaultdict(list)
    for t in tools:
        by_sub[t["subcategory"]].append(t)

    total = Counter(t["status"] for t in tools)
    live = sum(total[s] for s in ("built", "verified", "done"))
    has_content = lambda t: bool(t.get("content_html", "").strip())
    live_no_content = sum(1 for t in tools if t["status"] in ("built", "verified", "done") and not has_content(t))
    out = [
        "# Calculator build tracker",
        "",
        "Generated by `utilities/scaffold/tool_tracker.py` from `src/content/tools/*.json` — don't edit",
        "by hand. Change a tool's `status` in its JSON file, then re-run the script.",
        "",
        "Statuses: `planned` → `in_progress` → `built` (formula checked, page live) → `verified`",
        "(browser-tested) → `done`. Priority = number of competitor sites with the tool (3 = highest;",
        "old-site calculators are 3). Sites: C = calculator.net, D = dinkytown.net, F = fncalculator.com.",
        "Content: ✓ = the tool has its article (`content_html`) and FAQ; – = calculator only, content still to write.",
        "",
        f"**{live} of {len(tools)} live** · " + " · ".join(f"{s}: {total[s]}" for s in STATUSES)
        + f" · live without content: {live_no_content}",
        "",
        "## By subcategory",
        "",
        "| Subcategory | Tools | Live | In progress | Planned |",
        "|---|---:|---:|---:|---:|",
    ]
    for sub in sorted(by_sub, key=lambda s: order.get(s, 999)):
        c = Counter(t["status"] for t in by_sub[sub])
        out.append(f"| {subs.get(sub, sub)} | {len(by_sub[sub])} | "
                   f"{c['built'] + c['verified'] + c['done']} | {c['in_progress']} | {c['planned']} |")

    for sub in sorted(by_sub, key=lambda s: order.get(s, 999)):
        out += ["", f"## {subs.get(sub, sub)}", "", "| Pri | Tool | Status | Content | Sites | Notes |", "|---:|---|---|:---:|---|---|"]
        for t in sorted(by_sub[sub], key=lambda t: (-(t.get("priority") or 0), t.get("order", 0), t["slug"])):
            have = {c["site"] for c in (t.get("research") or {}).get("competitors", [])}
            sites = "".join(code for site, code in SITES if site in have) or "–"
            note = "port from archive" if t.get("legacy") else ""
            status = f"**{t['status']}**" if t["status"] != "planned" else "planned"
            content = "✓" if has_content(t) else "–"
            out.append(f"| {t.get('priority') or ''} | `{t['slug']}` | {status} | {content} | {sites} | {note} |")

    OUT.write_text("\n".join(out) + "\n")
    print(f"Wrote {OUT.relative_to(ROOT)}: {live}/{len(tools)} live")


if __name__ == "__main__":
    main()
